version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./php:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./php:/var/www/html
